package com.qastore.api.product;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/*
 * ============================================================
 * File: ProductEntity.java
 * Module: Product Persistence
 *
 * Responsibility:
 * Represents the database table used to persist products in MySQL.
 *
 * Interaction:
 * ProductRepository manages this entity using Spring Data JPA.
 * ProductJpaService converts this entity into the internal Product domain model.
 *
 * Design Pattern:
 * JPA Entity.
 *
 * Engineering Principles:
 * - Separation of concerns: persistence model is separated from API DTOs.
 * - Single Responsibility Principle: this class represents database state only.
 * - ORM mapping: maps Java fields to relational database columns.
 * ============================================================
 */

@Entity
@Table(name = "products")
public class ProductEntity {

    /*
     * Primary key generated by the database.
     *
     * GenerationType.IDENTITY is commonly used with MySQL auto-increment columns.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Product name.
     *
     * nullable = false means the database column cannot store null values.
     * length = 120 limits the maximum size at the schema level.
     */
    @Column(nullable = false, length = 120)
    private String name;

    /*
     * Product description.
     */
    @Column(nullable = false, length = 500)
    private String description;

    /*
     * Product price.
     *
     * precision = 10 means up to 10 digits in total.
     * scale = 2 means 2 decimal places.
     *
     * Example: 99999999.99
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /*
     * Available stock.
     */
    @Column(nullable = false)
    private Integer stock;

    /*
     * Logical status of the product.
     *
     * Later, DELETE operations can use this flag for soft deletion.
     */
    @Column(nullable = false)
    private Boolean active;

    /*
     * Creation timestamp.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /*
     * Protected no-args constructor required by JPA.
     *
     * JPA needs this constructor to create entity instances through reflection.
     */
    protected ProductEntity() {
    }

    /*
     * Public constructor used by the service layer and tests.
     *
     * The id is not included because it is generated by the database.
     */
    public ProductEntity(String name, String description, BigDecimal price, Integer stock, Boolean active) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.stock = stock;
        this.active = active;
    }

    /*
     * Lifecycle callback executed before inserting the entity.
     *
     * This avoids requiring the controller or service to manually assign createdAt.
     */
    @PrePersist
    void prePersist() {
        this.createdAt = LocalDateTime.now();

        if (this.active == null) {
            this.active = true;
        }
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public Integer getStock() {
        return stock;
    }

    public Boolean getActive() {
        return active;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}