package com.qastore.api.product;

import com.qastore.api.category.CategoryEntity;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/*
 * ============================================================
 * File: ProductEntity.java
 * Module: Product Persistence
 *
 * Responsibility:
 * Represents the database table used to persist products in MySQL.
 *
 * Interaction:
 * ProductRepository manages this entity using Spring Data JPA.
 * ProductJpaService converts this entity into the internal Product domain model.
 * Each product is related to one CategoryEntity through a many-to-one relationship.
 *
 * Design Pattern:
 * JPA Entity.
 *
 * Engineering Principles:
 * - Separation of concerns: persistence model is separated from API DTOs.
 * - Single Responsibility Principle: this class represents database state only.
 * - ORM mapping: maps Java fields and relationships to relational database structures.
 * ============================================================
 */

@Entity
@Table(name = "products")
public class ProductEntity {

    /*
     * Primary key generated by the database.
     *
     * GenerationType.IDENTITY is commonly used with MySQL auto-increment columns.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Product name.
     */
    @Column(nullable = false, length = 120)
    private String name;

    /*
     * Product description.
     */
    @Column(nullable = false, length = 500)
    private String description;

    /*
     * Product price.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /*
     * Available stock.
     */
    @Column(nullable = false)
    private Integer stock;

    /*
     * Logical status of the product.
     */
    @Column(nullable = false)
    private Boolean active;

    /*
     * Many products can belong to one category.
     *
     * FetchType.LAZY avoids loading category data unless it is needed.
     * optional = false means a product must always have a category.
     *
     * The foreign key column in the products table will be category_id.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private CategoryEntity category;

    /*
     * Creation timestamp.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /*
     * Protected no-args constructor required by JPA.
     */
    protected ProductEntity() {
    }

    /*
     * Public constructor used by the service layer, seeders and tests.
     */
    public ProductEntity(
            String name,
            String description,
            BigDecimal price,
            Integer stock,
            Boolean active,
            CategoryEntity category) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.stock = stock;
        this.active = active;
        this.category = category;
    }

    /*
     * Lifecycle callback executed before inserting the entity.
     */
    @PrePersist
    void prePersist() {
        this.createdAt = LocalDateTime.now();

        if (this.active == null) {
            this.active = true;
        }
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public Integer getStock() {
        return stock;
    }

    public Boolean getActive() {
        return active;
    }

    public CategoryEntity getCategory() {
        return category;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /*
     * Updates mutable product fields.
     *
     * This method keeps update behavior inside the entity instead of exposing
     * public setters for every field.
     */
    public void updateDetails(
            String name,
            String description,
            BigDecimal price,
            Integer stock,
            CategoryEntity category) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.stock = stock;
        this.category = category;
    }

    /*
     * Performs a logical deletion.
     *
     * The record remains in the database, but normal API queries will no longer
     * return it because repositories filter by active = true.
     */
    public void deactivate() {
        this.active = false;
    }
}